### ISSUE TITLE
score_loss,usp_loss

### ISSUE THREAD

**Issue by hello7623** [791136190/UnsuperPoint_PyTorch#5]
请问您的score_loss 和用于提升score的usp_loss最后稳定在多少，我训练的时候很快他们接近于0了

**Comment by 791136190** [comment]
具体是多少记不太清了，应该是在1附近。这里有一次之前训练的loss曲线，你可以参考一下
![image](https://user-images.githubusercontent.com/27891060/100822964-54f0ce00-348e-11eb-9476-4a59cbcdb362.png)

**Comment by hello7623** [comment]
![image](https://user-images.githubusercontent.com/36818370/100823122-971a0f80-348e-11eb-96c8-19794073c77c.png)
就是这里，我发现您的代码中，稳定是0.03，-0.08，但是我在训练我的代码的时候，这两项很快非常接近于零，并且整个网络预测的分数都非常接近于0.5，令人费解

**Comment by 791136190** [comment]
你可以看一下是不是其他地方的参数和我的设置不一样，还有数据增强部分是不一致的。

**Comment by litingsjj** [comment]
> 请问您的score_loss 和用于提升score的usp_loss最后稳定在多少，我训练的时候很快他们接近于0了
@hello7623
请问您使用求和训练，loss稳定之后是多少？训练几个epoch，loss还是好几千
